#!/bin/sh
cd email.maildir

echo email data
./scan
./charts
cd ..

echo Last.fm data
cd music.lastfm
./download
cd ..

echo Twitter data
cd microblog.twitter
./download
./charts
cd ..

echo All done!
